create table if not exists public.members (
  id bigint generated by default as identity primary key,
  user_id uuid unique references auth.users(id) on delete set null,
  email text not null unique,
  name text not null,
  role text not null default 'technician' check (role in ('manager', 'service_supervisor', 'technician')),
  requested_role text check (requested_role in ('manager', 'service_supervisor', 'technician')),
  approval_status text not null default 'unregistered' check (approval_status in ('unregistered', 'pending', 'approved')),
  language text not null default 'en' check (language in ('en', 'es')),
  active boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.work_orders (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  area text not null,
  category text not null,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high', 'emergency')),
  status text not null default 'open' check (status in ('open', 'assigned', 'in_progress', 'on_hold', 'completed')),
  assigned_to bigint references public.members(id) on delete set null,
  due_date date,
  created_by uuid references auth.users(id) on delete set null,
  completion_comment text,
  resident_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists members_user_id_idx on public.members(user_id);
create index if not exists work_orders_status_idx on public.work_orders(status);
create index if not exists work_orders_assigned_to_idx on public.work_orders(assigned_to);
create index if not exists work_orders_created_at_idx on public.work_orders(created_at desc);

alter table public.members enable row level security;
alter table public.work_orders enable row level security;

-- The browser never receives the service-role key. All operational reads and
-- writes pass through authenticated server routes that enforce app roles.
revoke all on public.members from anon, authenticated;
revoke all on public.work_orders from anon, authenticated;
